title: Gustavo Martinez - Científico de Datos
logo: /assets/img/logo.png
description: Apasionado por convertir datos en soluciones reales.
show_downloads: false
theme: jekyll-theme-minimal
<<<<<<< HEAD
=======

>>>>>>> e9799023fde2238dbc7956253e0c2fda11bf26f2
