title: Gustavo Martinez - Científico de Datos
logo: /assets/img/logo.png
description: Apasionado por convertir datos en soluciones reales.
gmail: successtotal21@gmail.com 
show_downloads: false
theme: jekyll-theme-minimal
gmail: 
